name: TheFlash
main: me.kihron.flash.Main
version: 1.0.0
commands:
    flashon:
        usage: <command>
        description: Enables Flash powers
    flashoff:
        usage: <command>
        description: Disables Flash powers